stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release 

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/cfg
        - cp -frv ./include/cfg $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libcfg.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libcfg.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_cfg $UT_PATH

    only:
        - master

shm:
    stage: trigger
    script:
        - curl -X POST -F token=6f59cf754820cfb5cb8b7fc95e14f8 -F ref=master $GITLAB_URL/api/v4/projects/11/trigger/pipeline
    only:
        - master
